version: '3.8'

services:
  drogueria:
    container_name: drogueria
    build:
      context: ./drogueria
      dockerfile: DockerFile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Drogueria/:/usr/src/drogueria
    ports:
      - 8000:8000
    env_file:
      - ./.env_dev

  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: drogueria
      POSTGRES_DB: drogueria